### ISSUE TITLE
Issue on Discovery primitives documentation

### ISSUE THREAD

**Issue by luisfpinto** [netbeast/bigfoot#2]
If you go to https://netbeast.gitbooks.io/bigfoot/chapter1.html and I see the example with the title "Scan" 

```
var Server = require('node-ssdp').Server

server = new Server({
  sourcePort: 1900,
})

server.addUSN('bigfoot:all')

server.start()

process.on('exit', function() {
  server.stop() // advertise shutting down and stop listening
})
```

**This is actually an annoucement on ssdp not a scan**. The application will do the Scan process after the hardware has launched the announcement message through ssdp on this case. 

So the process on the documentation should be:

1. Announcement using SSDP or other kind of method
2. Scan by Yeti
3. Ping

**Comment by luisfpinto** [comment]
Also, It should be nice if you could give access for contributing to the documentation I would be glad to contribute on this.

**Comment by jsdario** [comment]
Thanks @luisfpinto!

I synced gitbook with a github repo so it is more natural for contributors to create PRs and improve the docs. You can find it here https://github.com/netbeast/bigfoot-docs.

Also I will try to implement a monorepo structure so we only need to clone the repo once to contribute to both 🔥
